// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ManuelP84/calendar_notification/app"
	"github.com/ManuelP84/calendar_notification/business/task/handlers"
	"github.com/ManuelP84/calendar_notification/infra/config"
	"github.com/ManuelP84/calendar_notification/infra/mongo/task"
	"github.com/ManuelP84/calendar_notification/infra/rabbit/consumer"
)

// Injectors from wire.go:

func CreateApp() *app.App {
	appSettings := config.GetAppSettings()
	rabbitSettings := config.GetRabbitSettings()
	consumerConsumer := consumer.NewConsumer(rabbitSettings)
	mongoDbSettings := config.GetMongoSettings()
	mongoRepository := task.NewMongoRepository(mongoDbSettings)
	taskHandlers := handlers.NewTaskHandlers(mongoRepository)
	appApp := app.NewApp(appSettings, consumerConsumer, taskHandlers)
	return appApp
}
